/** Auto-ish EXTRA regions (non Seoul/Gyeonggi). Do not hand-edit bulk. */
import type { NationwideMetro } from "./nationwide-lawd";

/** regions-registry RegionDef 와 동일 shape (순환 import 방지) */
export type ExtraRegionDef = {
  slug: string;
  metro: NationwideMetro;
  name: string;
  fullName: string;
  lawdCodes: string[];
  districts: Array<{ code: string; name: string }>;
};

export const NATIONWIDE_EXTRA_REGIONS: ExtraRegionDef[] = [
  { slug: "busan-26110", metro: "busan", name: "중구", fullName: "부산광역시 중구", lawdCodes: ["26110"], districts: [{ code: "26110", name: "중구" }] },
  { slug: "busan-26140", metro: "busan", name: "서구", fullName: "부산광역시 서구", lawdCodes: ["26140"], districts: [{ code: "26140", name: "서구" }] },
  { slug: "busan-26170", metro: "busan", name: "동구", fullName: "부산광역시 동구", lawdCodes: ["26170"], districts: [{ code: "26170", name: "동구" }] },
  { slug: "busan-26200", metro: "busan", name: "영도구", fullName: "부산광역시 영도구", lawdCodes: ["26200"], districts: [{ code: "26200", name: "영도구" }] },
  { slug: "busan-26230", metro: "busan", name: "부산진구", fullName: "부산광역시 부산진구", lawdCodes: ["26230"], districts: [{ code: "26230", name: "부산진구" }] },
  { slug: "busan-26260", metro: "busan", name: "동래구", fullName: "부산광역시 동래구", lawdCodes: ["26260"], districts: [{ code: "26260", name: "동래구" }] },
  { slug: "busan-26290", metro: "busan", name: "남구", fullName: "부산광역시 남구", lawdCodes: ["26290"], districts: [{ code: "26290", name: "남구" }] },
  { slug: "busan-26320", metro: "busan", name: "북구", fullName: "부산광역시 북구", lawdCodes: ["26320"], districts: [{ code: "26320", name: "북구" }] },
  { slug: "busan-26350", metro: "busan", name: "해운대구", fullName: "부산광역시 해운대구", lawdCodes: ["26350"], districts: [{ code: "26350", name: "해운대구" }] },
  { slug: "busan-26380", metro: "busan", name: "사하구", fullName: "부산광역시 사하구", lawdCodes: ["26380"], districts: [{ code: "26380", name: "사하구" }] },
  { slug: "busan-26410", metro: "busan", name: "금정구", fullName: "부산광역시 금정구", lawdCodes: ["26410"], districts: [{ code: "26410", name: "금정구" }] },
  { slug: "busan-26440", metro: "busan", name: "강서구", fullName: "부산광역시 강서구", lawdCodes: ["26440"], districts: [{ code: "26440", name: "강서구" }] },
  { slug: "busan-26470", metro: "busan", name: "연제구", fullName: "부산광역시 연제구", lawdCodes: ["26470"], districts: [{ code: "26470", name: "연제구" }] },
  { slug: "busan-26500", metro: "busan", name: "수영구", fullName: "부산광역시 수영구", lawdCodes: ["26500"], districts: [{ code: "26500", name: "수영구" }] },
  { slug: "busan-26530", metro: "busan", name: "사상구", fullName: "부산광역시 사상구", lawdCodes: ["26530"], districts: [{ code: "26530", name: "사상구" }] },
  { slug: "busan-26710", metro: "busan", name: "기장군", fullName: "부산광역시 기장군", lawdCodes: ["26710"], districts: [{ code: "26710", name: "기장군" }] },
  { slug: "daegu-27110", metro: "daegu", name: "중구", fullName: "대구광역시 중구", lawdCodes: ["27110"], districts: [{ code: "27110", name: "중구" }] },
  { slug: "daegu-27140", metro: "daegu", name: "동구", fullName: "대구광역시 동구", lawdCodes: ["27140"], districts: [{ code: "27140", name: "동구" }] },
  { slug: "daegu-27170", metro: "daegu", name: "서구", fullName: "대구광역시 서구", lawdCodes: ["27170"], districts: [{ code: "27170", name: "서구" }] },
  { slug: "daegu-27200", metro: "daegu", name: "남구", fullName: "대구광역시 남구", lawdCodes: ["27200"], districts: [{ code: "27200", name: "남구" }] },
  { slug: "daegu-27230", metro: "daegu", name: "북구", fullName: "대구광역시 북구", lawdCodes: ["27230"], districts: [{ code: "27230", name: "북구" }] },
  { slug: "daegu-27260", metro: "daegu", name: "수성구", fullName: "대구광역시 수성구", lawdCodes: ["27260"], districts: [{ code: "27260", name: "수성구" }] },
  { slug: "daegu-27290", metro: "daegu", name: "달서구", fullName: "대구광역시 달서구", lawdCodes: ["27290"], districts: [{ code: "27290", name: "달서구" }] },
  { slug: "daegu-27710", metro: "daegu", name: "달성군", fullName: "대구광역시 달성군", lawdCodes: ["27710"], districts: [{ code: "27710", name: "달성군" }] },
  { slug: "incheon-28110", metro: "incheon", name: "중구", fullName: "인천광역시 중구", lawdCodes: ["28110"], districts: [{ code: "28110", name: "중구" }] },
  { slug: "incheon-28140", metro: "incheon", name: "동구", fullName: "인천광역시 동구", lawdCodes: ["28140"], districts: [{ code: "28140", name: "동구" }] },
  { slug: "incheon-28177", metro: "incheon", name: "미추홀구", fullName: "인천광역시 미추홀구", lawdCodes: ["28177"], districts: [{ code: "28177", name: "미추홀구" }] },
  { slug: "incheon-28185", metro: "incheon", name: "연수구", fullName: "인천광역시 연수구", lawdCodes: ["28185"], districts: [{ code: "28185", name: "연수구" }] },
  { slug: "incheon-28200", metro: "incheon", name: "남동구", fullName: "인천광역시 남동구", lawdCodes: ["28200"], districts: [{ code: "28200", name: "남동구" }] },
  { slug: "incheon-28237", metro: "incheon", name: "부평구", fullName: "인천광역시 부평구", lawdCodes: ["28237"], districts: [{ code: "28237", name: "부평구" }] },
  { slug: "incheon-28245", metro: "incheon", name: "계양구", fullName: "인천광역시 계양구", lawdCodes: ["28245"], districts: [{ code: "28245", name: "계양구" }] },
  { slug: "incheon-28260", metro: "incheon", name: "서구", fullName: "인천광역시 서구", lawdCodes: ["28260"], districts: [{ code: "28260", name: "서구" }] },
  { slug: "incheon-28710", metro: "incheon", name: "강화군", fullName: "인천광역시 강화군", lawdCodes: ["28710"], districts: [{ code: "28710", name: "강화군" }] },
  { slug: "incheon-28720", metro: "incheon", name: "옹진군", fullName: "인천광역시 옹진군", lawdCodes: ["28720"], districts: [{ code: "28720", name: "옹진군" }] },
  { slug: "gwangju-29110", metro: "gwangju", name: "동구", fullName: "광주광역시 동구", lawdCodes: ["29110"], districts: [{ code: "29110", name: "동구" }] },
  { slug: "gwangju-29140", metro: "gwangju", name: "서구", fullName: "광주광역시 서구", lawdCodes: ["29140"], districts: [{ code: "29140", name: "서구" }] },
  { slug: "gwangju-29155", metro: "gwangju", name: "남구", fullName: "광주광역시 남구", lawdCodes: ["29155"], districts: [{ code: "29155", name: "남구" }] },
  { slug: "gwangju-29170", metro: "gwangju", name: "북구", fullName: "광주광역시 북구", lawdCodes: ["29170"], districts: [{ code: "29170", name: "북구" }] },
  { slug: "gwangju-29200", metro: "gwangju", name: "광산구", fullName: "광주광역시 광산구", lawdCodes: ["29200"], districts: [{ code: "29200", name: "광산구" }] },
  { slug: "daejeon-30110", metro: "daejeon", name: "동구", fullName: "대전광역시 동구", lawdCodes: ["30110"], districts: [{ code: "30110", name: "동구" }] },
  { slug: "daejeon-30140", metro: "daejeon", name: "중구", fullName: "대전광역시 중구", lawdCodes: ["30140"], districts: [{ code: "30140", name: "중구" }] },
  { slug: "daejeon-30170", metro: "daejeon", name: "서구", fullName: "대전광역시 서구", lawdCodes: ["30170"], districts: [{ code: "30170", name: "서구" }] },
  { slug: "daejeon-30200", metro: "daejeon", name: "유성구", fullName: "대전광역시 유성구", lawdCodes: ["30200"], districts: [{ code: "30200", name: "유성구" }] },
  { slug: "daejeon-30230", metro: "daejeon", name: "대덕구", fullName: "대전광역시 대덕구", lawdCodes: ["30230"], districts: [{ code: "30230", name: "대덕구" }] },
  { slug: "ulsan-31110", metro: "ulsan", name: "중구", fullName: "울산광역시 중구", lawdCodes: ["31110"], districts: [{ code: "31110", name: "중구" }] },
  { slug: "ulsan-31140", metro: "ulsan", name: "남구", fullName: "울산광역시 남구", lawdCodes: ["31140"], districts: [{ code: "31140", name: "남구" }] },
  { slug: "ulsan-31170", metro: "ulsan", name: "동구", fullName: "울산광역시 동구", lawdCodes: ["31170"], districts: [{ code: "31170", name: "동구" }] },
  { slug: "ulsan-31200", metro: "ulsan", name: "북구", fullName: "울산광역시 북구", lawdCodes: ["31200"], districts: [{ code: "31200", name: "북구" }] },
  { slug: "ulsan-31710", metro: "ulsan", name: "울주군", fullName: "울산광역시 울주군", lawdCodes: ["31710"], districts: [{ code: "31710", name: "울주군" }] },
  { slug: "sejong-36110", metro: "sejong", name: "세종특별자치시", fullName: "세종특별자치시", lawdCodes: ["36110"], districts: [{ code: "36110", name: "세종특별자치시" }] },
  { slug: "gangwon-42110", metro: "gangwon", name: "춘천시", fullName: "강원특별자치도 춘천시", lawdCodes: ["42110"], districts: [{ code: "42110", name: "춘천시" }] },
  { slug: "gangwon-42130", metro: "gangwon", name: "원주시", fullName: "강원특별자치도 원주시", lawdCodes: ["42130"], districts: [{ code: "42130", name: "원주시" }] },
  { slug: "gangwon-42150", metro: "gangwon", name: "강릉시", fullName: "강원특별자치도 강릉시", lawdCodes: ["42150"], districts: [{ code: "42150", name: "강릉시" }] },
  { slug: "gangwon-42170", metro: "gangwon", name: "동해시", fullName: "강원특별자치도 동해시", lawdCodes: ["42170"], districts: [{ code: "42170", name: "동해시" }] },
  { slug: "gangwon-42190", metro: "gangwon", name: "태백시", fullName: "강원특별자치도 태백시", lawdCodes: ["42190"], districts: [{ code: "42190", name: "태백시" }] },
  { slug: "gangwon-42210", metro: "gangwon", name: "속초시", fullName: "강원특별자치도 속초시", lawdCodes: ["42210"], districts: [{ code: "42210", name: "속초시" }] },
  { slug: "gangwon-42230", metro: "gangwon", name: "삼척시", fullName: "강원특별자치도 삼척시", lawdCodes: ["42230"], districts: [{ code: "42230", name: "삼척시" }] },
  { slug: "gangwon-42720", metro: "gangwon", name: "홍천군", fullName: "강원특별자치도 홍천군", lawdCodes: ["42720"], districts: [{ code: "42720", name: "홍천군" }] },
  { slug: "gangwon-42730", metro: "gangwon", name: "횡성군", fullName: "강원특별자치도 횡성군", lawdCodes: ["42730"], districts: [{ code: "42730", name: "횡성군" }] },
  { slug: "gangwon-42750", metro: "gangwon", name: "영월군", fullName: "강원특별자치도 영월군", lawdCodes: ["42750"], districts: [{ code: "42750", name: "영월군" }] },
  { slug: "gangwon-42760", metro: "gangwon", name: "평창군", fullName: "강원특별자치도 평창군", lawdCodes: ["42760"], districts: [{ code: "42760", name: "평창군" }] },
  { slug: "gangwon-42770", metro: "gangwon", name: "정선군", fullName: "강원특별자치도 정선군", lawdCodes: ["42770"], districts: [{ code: "42770", name: "정선군" }] },
  { slug: "gangwon-42780", metro: "gangwon", name: "철원군", fullName: "강원특별자치도 철원군", lawdCodes: ["42780"], districts: [{ code: "42780", name: "철원군" }] },
  { slug: "gangwon-42790", metro: "gangwon", name: "화천군", fullName: "강원특별자치도 화천군", lawdCodes: ["42790"], districts: [{ code: "42790", name: "화천군" }] },
  { slug: "gangwon-42800", metro: "gangwon", name: "양구군", fullName: "강원특별자치도 양구군", lawdCodes: ["42800"], districts: [{ code: "42800", name: "양구군" }] },
  { slug: "gangwon-42810", metro: "gangwon", name: "인제군", fullName: "강원특별자치도 인제군", lawdCodes: ["42810"], districts: [{ code: "42810", name: "인제군" }] },
  { slug: "gangwon-42820", metro: "gangwon", name: "고성군", fullName: "강원특별자치도 고성군", lawdCodes: ["42820"], districts: [{ code: "42820", name: "고성군" }] },
  { slug: "gangwon-42830", metro: "gangwon", name: "양양군", fullName: "강원특별자치도 양양군", lawdCodes: ["42830"], districts: [{ code: "42830", name: "양양군" }] },
  { slug: "chungbuk-43111", metro: "chungbuk", name: "청주시 상당구", fullName: "충청북도 청주시 상당구", lawdCodes: ["43111"], districts: [{ code: "43111", name: "상당구" }] },
  { slug: "chungbuk-43112", metro: "chungbuk", name: "청주시 서원구", fullName: "충청북도 청주시 서원구", lawdCodes: ["43112"], districts: [{ code: "43112", name: "서원구" }] },
  { slug: "chungbuk-43113", metro: "chungbuk", name: "청주시 흥덕구", fullName: "충청북도 청주시 흥덕구", lawdCodes: ["43113"], districts: [{ code: "43113", name: "흥덕구" }] },
  { slug: "chungbuk-43114", metro: "chungbuk", name: "청주시 청원구", fullName: "충청북도 청주시 청원구", lawdCodes: ["43114"], districts: [{ code: "43114", name: "청원구" }] },
  { slug: "chungbuk-43130", metro: "chungbuk", name: "충주시", fullName: "충청북도 충주시", lawdCodes: ["43130"], districts: [{ code: "43130", name: "충주시" }] },
  { slug: "chungbuk-43150", metro: "chungbuk", name: "제천시", fullName: "충청북도 제천시", lawdCodes: ["43150"], districts: [{ code: "43150", name: "제천시" }] },
  { slug: "chungbuk-43720", metro: "chungbuk", name: "보은군", fullName: "충청북도 보은군", lawdCodes: ["43720"], districts: [{ code: "43720", name: "보은군" }] },
  { slug: "chungbuk-43730", metro: "chungbuk", name: "옥천군", fullName: "충청북도 옥천군", lawdCodes: ["43730"], districts: [{ code: "43730", name: "옥천군" }] },
  { slug: "chungbuk-43740", metro: "chungbuk", name: "영동군", fullName: "충청북도 영동군", lawdCodes: ["43740"], districts: [{ code: "43740", name: "영동군" }] },
  { slug: "chungbuk-43745", metro: "chungbuk", name: "증평군", fullName: "충청북도 증평군", lawdCodes: ["43745"], districts: [{ code: "43745", name: "증평군" }] },
  { slug: "chungbuk-43750", metro: "chungbuk", name: "진천군", fullName: "충청북도 진천군", lawdCodes: ["43750"], districts: [{ code: "43750", name: "진천군" }] },
  { slug: "chungbuk-43760", metro: "chungbuk", name: "괴산군", fullName: "충청북도 괴산군", lawdCodes: ["43760"], districts: [{ code: "43760", name: "괴산군" }] },
  { slug: "chungbuk-43770", metro: "chungbuk", name: "음성군", fullName: "충청북도 음성군", lawdCodes: ["43770"], districts: [{ code: "43770", name: "음성군" }] },
  { slug: "chungbuk-43800", metro: "chungbuk", name: "단양군", fullName: "충청북도 단양군", lawdCodes: ["43800"], districts: [{ code: "43800", name: "단양군" }] },
  { slug: "chungnam-44131", metro: "chungnam", name: "천안시 동남구", fullName: "충청남도 천안시 동남구", lawdCodes: ["44131"], districts: [{ code: "44131", name: "동남구" }] },
  { slug: "chungnam-44133", metro: "chungnam", name: "천안시 서북구", fullName: "충청남도 천안시 서북구", lawdCodes: ["44133"], districts: [{ code: "44133", name: "서북구" }] },
  { slug: "chungnam-44150", metro: "chungnam", name: "공주시", fullName: "충청남도 공주시", lawdCodes: ["44150"], districts: [{ code: "44150", name: "공주시" }] },
  { slug: "chungnam-44180", metro: "chungnam", name: "보령시", fullName: "충청남도 보령시", lawdCodes: ["44180"], districts: [{ code: "44180", name: "보령시" }] },
  { slug: "chungnam-44200", metro: "chungnam", name: "아산시", fullName: "충청남도 아산시", lawdCodes: ["44200"], districts: [{ code: "44200", name: "아산시" }] },
  { slug: "chungnam-44210", metro: "chungnam", name: "서산시", fullName: "충청남도 서산시", lawdCodes: ["44210"], districts: [{ code: "44210", name: "서산시" }] },
  { slug: "chungnam-44230", metro: "chungnam", name: "논산시", fullName: "충청남도 논산시", lawdCodes: ["44230"], districts: [{ code: "44230", name: "논산시" }] },
  { slug: "chungnam-44250", metro: "chungnam", name: "계룡시", fullName: "충청남도 계룡시", lawdCodes: ["44250"], districts: [{ code: "44250", name: "계룡시" }] },
  { slug: "chungnam-44270", metro: "chungnam", name: "당진시", fullName: "충청남도 당진시", lawdCodes: ["44270"], districts: [{ code: "44270", name: "당진시" }] },
  { slug: "chungnam-44710", metro: "chungnam", name: "금산군", fullName: "충청남도 금산군", lawdCodes: ["44710"], districts: [{ code: "44710", name: "금산군" }] },
  { slug: "chungnam-44760", metro: "chungnam", name: "부여군", fullName: "충청남도 부여군", lawdCodes: ["44760"], districts: [{ code: "44760", name: "부여군" }] },
  { slug: "chungnam-44770", metro: "chungnam", name: "서천군", fullName: "충청남도 서천군", lawdCodes: ["44770"], districts: [{ code: "44770", name: "서천군" }] },
  { slug: "chungnam-44790", metro: "chungnam", name: "청양군", fullName: "충청남도 청양군", lawdCodes: ["44790"], districts: [{ code: "44790", name: "청양군" }] },
  { slug: "chungnam-44800", metro: "chungnam", name: "홍성군", fullName: "충청남도 홍성군", lawdCodes: ["44800"], districts: [{ code: "44800", name: "홍성군" }] },
  { slug: "chungnam-44810", metro: "chungnam", name: "예산군", fullName: "충청남도 예산군", lawdCodes: ["44810"], districts: [{ code: "44810", name: "예산군" }] },
  { slug: "chungnam-44825", metro: "chungnam", name: "태안군", fullName: "충청남도 태안군", lawdCodes: ["44825"], districts: [{ code: "44825", name: "태안군" }] },
  { slug: "jeonbuk-45111", metro: "jeonbuk", name: "전주시 완산구", fullName: "전북특별자치도 전주시 완산구", lawdCodes: ["45111"], districts: [{ code: "45111", name: "완산구" }] },
  { slug: "jeonbuk-45113", metro: "jeonbuk", name: "전주시 덕진구", fullName: "전북특별자치도 전주시 덕진구", lawdCodes: ["45113"], districts: [{ code: "45113", name: "덕진구" }] },
  { slug: "jeonbuk-45130", metro: "jeonbuk", name: "군산시", fullName: "전북특별자치도 군산시", lawdCodes: ["45130"], districts: [{ code: "45130", name: "군산시" }] },
  { slug: "jeonbuk-45140", metro: "jeonbuk", name: "익산시", fullName: "전북특별자치도 익산시", lawdCodes: ["45140"], districts: [{ code: "45140", name: "익산시" }] },
  { slug: "jeonbuk-45180", metro: "jeonbuk", name: "정읍시", fullName: "전북특별자치도 정읍시", lawdCodes: ["45180"], districts: [{ code: "45180", name: "정읍시" }] },
  { slug: "jeonbuk-45190", metro: "jeonbuk", name: "남원시", fullName: "전북특별자치도 남원시", lawdCodes: ["45190"], districts: [{ code: "45190", name: "남원시" }] },
  { slug: "jeonbuk-45210", metro: "jeonbuk", name: "김제시", fullName: "전북특별자치도 김제시", lawdCodes: ["45210"], districts: [{ code: "45210", name: "김제시" }] },
  { slug: "jeonbuk-45710", metro: "jeonbuk", name: "완주군", fullName: "전북특별자치도 완주군", lawdCodes: ["45710"], districts: [{ code: "45710", name: "완주군" }] },
  { slug: "jeonbuk-45720", metro: "jeonbuk", name: "진안군", fullName: "전북특별자치도 진안군", lawdCodes: ["45720"], districts: [{ code: "45720", name: "진안군" }] },
  { slug: "jeonbuk-45730", metro: "jeonbuk", name: "무주군", fullName: "전북특별자치도 무주군", lawdCodes: ["45730"], districts: [{ code: "45730", name: "무주군" }] },
  { slug: "jeonbuk-45740", metro: "jeonbuk", name: "장수군", fullName: "전북특별자치도 장수군", lawdCodes: ["45740"], districts: [{ code: "45740", name: "장수군" }] },
  { slug: "jeonbuk-45750", metro: "jeonbuk", name: "임실군", fullName: "전북특별자치도 임실군", lawdCodes: ["45750"], districts: [{ code: "45750", name: "임실군" }] },
  { slug: "jeonbuk-45770", metro: "jeonbuk", name: "순창군", fullName: "전북특별자치도 순창군", lawdCodes: ["45770"], districts: [{ code: "45770", name: "순창군" }] },
  { slug: "jeonbuk-45790", metro: "jeonbuk", name: "고창군", fullName: "전북특별자치도 고창군", lawdCodes: ["45790"], districts: [{ code: "45790", name: "고창군" }] },
  { slug: "jeonbuk-45800", metro: "jeonbuk", name: "부안군", fullName: "전북특별자치도 부안군", lawdCodes: ["45800"], districts: [{ code: "45800", name: "부안군" }] },
  { slug: "jeonnam-46110", metro: "jeonnam", name: "목포시", fullName: "전라남도 목포시", lawdCodes: ["46110"], districts: [{ code: "46110", name: "목포시" }] },
  { slug: "jeonnam-46130", metro: "jeonnam", name: "여수시", fullName: "전라남도 여수시", lawdCodes: ["46130"], districts: [{ code: "46130", name: "여수시" }] },
  { slug: "jeonnam-46150", metro: "jeonnam", name: "순천시", fullName: "전라남도 순천시", lawdCodes: ["46150"], districts: [{ code: "46150", name: "순천시" }] },
  { slug: "jeonnam-46170", metro: "jeonnam", name: "나주시", fullName: "전라남도 나주시", lawdCodes: ["46170"], districts: [{ code: "46170", name: "나주시" }] },
  { slug: "jeonnam-46230", metro: "jeonnam", name: "광양시", fullName: "전라남도 광양시", lawdCodes: ["46230"], districts: [{ code: "46230", name: "광양시" }] },
  { slug: "jeonnam-46710", metro: "jeonnam", name: "담양군", fullName: "전라남도 담양군", lawdCodes: ["46710"], districts: [{ code: "46710", name: "담양군" }] },
  { slug: "jeonnam-46720", metro: "jeonnam", name: "곡성군", fullName: "전라남도 곡성군", lawdCodes: ["46720"], districts: [{ code: "46720", name: "곡성군" }] },
  { slug: "jeonnam-46730", metro: "jeonnam", name: "구례군", fullName: "전라남도 구례군", lawdCodes: ["46730"], districts: [{ code: "46730", name: "구례군" }] },
  { slug: "jeonnam-46770", metro: "jeonnam", name: "고흥군", fullName: "전라남도 고흥군", lawdCodes: ["46770"], districts: [{ code: "46770", name: "고흥군" }] },
  { slug: "jeonnam-46780", metro: "jeonnam", name: "보성군", fullName: "전라남도 보성군", lawdCodes: ["46780"], districts: [{ code: "46780", name: "보성군" }] },
  { slug: "jeonnam-46790", metro: "jeonnam", name: "화순군", fullName: "전라남도 화순군", lawdCodes: ["46790"], districts: [{ code: "46790", name: "화순군" }] },
  { slug: "jeonnam-46800", metro: "jeonnam", name: "장흥군", fullName: "전라남도 장흥군", lawdCodes: ["46800"], districts: [{ code: "46800", name: "장흥군" }] },
  { slug: "jeonnam-46810", metro: "jeonnam", name: "강진군", fullName: "전라남도 강진군", lawdCodes: ["46810"], districts: [{ code: "46810", name: "강진군" }] },
  { slug: "jeonnam-46820", metro: "jeonnam", name: "해남군", fullName: "전라남도 해남군", lawdCodes: ["46820"], districts: [{ code: "46820", name: "해남군" }] },
  { slug: "jeonnam-46830", metro: "jeonnam", name: "영암군", fullName: "전라남도 영암군", lawdCodes: ["46830"], districts: [{ code: "46830", name: "영암군" }] },
  { slug: "jeonnam-46840", metro: "jeonnam", name: "무안군", fullName: "전라남도 무안군", lawdCodes: ["46840"], districts: [{ code: "46840", name: "무안군" }] },
  { slug: "jeonnam-46860", metro: "jeonnam", name: "함평군", fullName: "전라남도 함평군", lawdCodes: ["46860"], districts: [{ code: "46860", name: "함평군" }] },
  { slug: "jeonnam-46870", metro: "jeonnam", name: "영광군", fullName: "전라남도 영광군", lawdCodes: ["46870"], districts: [{ code: "46870", name: "영광군" }] },
  { slug: "jeonnam-46880", metro: "jeonnam", name: "장성군", fullName: "전라남도 장성군", lawdCodes: ["46880"], districts: [{ code: "46880", name: "장성군" }] },
  { slug: "jeonnam-46890", metro: "jeonnam", name: "완도군", fullName: "전라남도 완도군", lawdCodes: ["46890"], districts: [{ code: "46890", name: "완도군" }] },
  { slug: "jeonnam-46900", metro: "jeonnam", name: "진도군", fullName: "전라남도 진도군", lawdCodes: ["46900"], districts: [{ code: "46900", name: "진도군" }] },
  { slug: "jeonnam-46910", metro: "jeonnam", name: "신안군", fullName: "전라남도 신안군", lawdCodes: ["46910"], districts: [{ code: "46910", name: "신안군" }] },
  { slug: "gyeongbuk-47111", metro: "gyeongbuk", name: "포항시 남구", fullName: "경상북도 포항시 남구", lawdCodes: ["47111"], districts: [{ code: "47111", name: "남구" }] },
  { slug: "gyeongbuk-47113", metro: "gyeongbuk", name: "포항시 북구", fullName: "경상북도 포항시 북구", lawdCodes: ["47113"], districts: [{ code: "47113", name: "북구" }] },
  { slug: "gyeongbuk-47130", metro: "gyeongbuk", name: "경주시", fullName: "경상북도 경주시", lawdCodes: ["47130"], districts: [{ code: "47130", name: "경주시" }] },
  { slug: "gyeongbuk-47150", metro: "gyeongbuk", name: "김천시", fullName: "경상북도 김천시", lawdCodes: ["47150"], districts: [{ code: "47150", name: "김천시" }] },
  { slug: "gyeongbuk-47170", metro: "gyeongbuk", name: "안동시", fullName: "경상북도 안동시", lawdCodes: ["47170"], districts: [{ code: "47170", name: "안동시" }] },
  { slug: "gyeongbuk-47190", metro: "gyeongbuk", name: "구미시", fullName: "경상북도 구미시", lawdCodes: ["47190"], districts: [{ code: "47190", name: "구미시" }] },
  { slug: "gyeongbuk-47210", metro: "gyeongbuk", name: "영주시", fullName: "경상북도 영주시", lawdCodes: ["47210"], districts: [{ code: "47210", name: "영주시" }] },
  { slug: "gyeongbuk-47230", metro: "gyeongbuk", name: "영천시", fullName: "경상북도 영천시", lawdCodes: ["47230"], districts: [{ code: "47230", name: "영천시" }] },
  { slug: "gyeongbuk-47250", metro: "gyeongbuk", name: "상주시", fullName: "경상북도 상주시", lawdCodes: ["47250"], districts: [{ code: "47250", name: "상주시" }] },
  { slug: "gyeongbuk-47280", metro: "gyeongbuk", name: "문경시", fullName: "경상북도 문경시", lawdCodes: ["47280"], districts: [{ code: "47280", name: "문경시" }] },
  { slug: "gyeongbuk-47290", metro: "gyeongbuk", name: "경산시", fullName: "경상북도 경산시", lawdCodes: ["47290"], districts: [{ code: "47290", name: "경산시" }] },
  { slug: "gyeongbuk-47730", metro: "gyeongbuk", name: "의성군", fullName: "경상북도 의성군", lawdCodes: ["47730"], districts: [{ code: "47730", name: "의성군" }] },
  { slug: "gyeongbuk-47750", metro: "gyeongbuk", name: "청송군", fullName: "경상북도 청송군", lawdCodes: ["47750"], districts: [{ code: "47750", name: "청송군" }] },
  { slug: "gyeongbuk-47760", metro: "gyeongbuk", name: "영양군", fullName: "경상북도 영양군", lawdCodes: ["47760"], districts: [{ code: "47760", name: "영양군" }] },
  { slug: "gyeongbuk-47770", metro: "gyeongbuk", name: "영덕군", fullName: "경상북도 영덕군", lawdCodes: ["47770"], districts: [{ code: "47770", name: "영덕군" }] },
  { slug: "gyeongbuk-47820", metro: "gyeongbuk", name: "청도군", fullName: "경상북도 청도군", lawdCodes: ["47820"], districts: [{ code: "47820", name: "청도군" }] },
  { slug: "gyeongbuk-47830", metro: "gyeongbuk", name: "고령군", fullName: "경상북도 고령군", lawdCodes: ["47830"], districts: [{ code: "47830", name: "고령군" }] },
  { slug: "gyeongbuk-47840", metro: "gyeongbuk", name: "성주군", fullName: "경상북도 성주군", lawdCodes: ["47840"], districts: [{ code: "47840", name: "성주군" }] },
  { slug: "gyeongbuk-47850", metro: "gyeongbuk", name: "칠곡군", fullName: "경상북도 칠곡군", lawdCodes: ["47850"], districts: [{ code: "47850", name: "칠곡군" }] },
  { slug: "gyeongbuk-47900", metro: "gyeongbuk", name: "예천군", fullName: "경상북도 예천군", lawdCodes: ["47900"], districts: [{ code: "47900", name: "예천군" }] },
  { slug: "gyeongbuk-47920", metro: "gyeongbuk", name: "봉화군", fullName: "경상북도 봉화군", lawdCodes: ["47920"], districts: [{ code: "47920", name: "봉화군" }] },
  { slug: "gyeongbuk-47930", metro: "gyeongbuk", name: "울진군", fullName: "경상북도 울진군", lawdCodes: ["47930"], districts: [{ code: "47930", name: "울진군" }] },
  { slug: "gyeongbuk-47940", metro: "gyeongbuk", name: "울릉군", fullName: "경상북도 울릉군", lawdCodes: ["47940"], districts: [{ code: "47940", name: "울릉군" }] },
  { slug: "gyeongnam-48121", metro: "gyeongnam", name: "창원시 의창구", fullName: "경상남도 창원시 의창구", lawdCodes: ["48121"], districts: [{ code: "48121", name: "의창구" }] },
  { slug: "gyeongnam-48123", metro: "gyeongnam", name: "창원시 성산구", fullName: "경상남도 창원시 성산구", lawdCodes: ["48123"], districts: [{ code: "48123", name: "성산구" }] },
  { slug: "gyeongnam-48125", metro: "gyeongnam", name: "창원시 마산합포구", fullName: "경상남도 창원시 마산합포구", lawdCodes: ["48125"], districts: [{ code: "48125", name: "마산합포구" }] },
  { slug: "gyeongnam-48127", metro: "gyeongnam", name: "창원시 마산회원구", fullName: "경상남도 창원시 마산회원구", lawdCodes: ["48127"], districts: [{ code: "48127", name: "마산회원구" }] },
  { slug: "gyeongnam-48129", metro: "gyeongnam", name: "창원시 진해구", fullName: "경상남도 창원시 진해구", lawdCodes: ["48129"], districts: [{ code: "48129", name: "진해구" }] },
  { slug: "gyeongnam-48170", metro: "gyeongnam", name: "진주시", fullName: "경상남도 진주시", lawdCodes: ["48170"], districts: [{ code: "48170", name: "진주시" }] },
  { slug: "gyeongnam-48220", metro: "gyeongnam", name: "통영시", fullName: "경상남도 통영시", lawdCodes: ["48220"], districts: [{ code: "48220", name: "통영시" }] },
  { slug: "gyeongnam-48240", metro: "gyeongnam", name: "사천시", fullName: "경상남도 사천시", lawdCodes: ["48240"], districts: [{ code: "48240", name: "사천시" }] },
  { slug: "gyeongnam-48250", metro: "gyeongnam", name: "김해시", fullName: "경상남도 김해시", lawdCodes: ["48250"], districts: [{ code: "48250", name: "김해시" }] },
  { slug: "gyeongnam-48270", metro: "gyeongnam", name: "밀양시", fullName: "경상남도 밀양시", lawdCodes: ["48270"], districts: [{ code: "48270", name: "밀양시" }] },
  { slug: "gyeongnam-48310", metro: "gyeongnam", name: "거제시", fullName: "경상남도 거제시", lawdCodes: ["48310"], districts: [{ code: "48310", name: "거제시" }] },
  { slug: "gyeongnam-48330", metro: "gyeongnam", name: "양산시", fullName: "경상남도 양산시", lawdCodes: ["48330"], districts: [{ code: "48330", name: "양산시" }] },
  { slug: "gyeongnam-48720", metro: "gyeongnam", name: "의령군", fullName: "경상남도 의령군", lawdCodes: ["48720"], districts: [{ code: "48720", name: "의령군" }] },
  { slug: "gyeongnam-48730", metro: "gyeongnam", name: "함안군", fullName: "경상남도 함안군", lawdCodes: ["48730"], districts: [{ code: "48730", name: "함안군" }] },
  { slug: "gyeongnam-48740", metro: "gyeongnam", name: "창녕군", fullName: "경상남도 창녕군", lawdCodes: ["48740"], districts: [{ code: "48740", name: "창녕군" }] },
  { slug: "gyeongnam-48820", metro: "gyeongnam", name: "고성군", fullName: "경상남도 고성군", lawdCodes: ["48820"], districts: [{ code: "48820", name: "고성군" }] },
  { slug: "gyeongnam-48840", metro: "gyeongnam", name: "남해군", fullName: "경상남도 남해군", lawdCodes: ["48840"], districts: [{ code: "48840", name: "남해군" }] },
  { slug: "gyeongnam-48850", metro: "gyeongnam", name: "하동군", fullName: "경상남도 하동군", lawdCodes: ["48850"], districts: [{ code: "48850", name: "하동군" }] },
  { slug: "gyeongnam-48860", metro: "gyeongnam", name: "산청군", fullName: "경상남도 산청군", lawdCodes: ["48860"], districts: [{ code: "48860", name: "산청군" }] },
  { slug: "gyeongnam-48870", metro: "gyeongnam", name: "함양군", fullName: "경상남도 함양군", lawdCodes: ["48870"], districts: [{ code: "48870", name: "함양군" }] },
  { slug: "gyeongnam-48880", metro: "gyeongnam", name: "거창군", fullName: "경상남도 거창군", lawdCodes: ["48880"], districts: [{ code: "48880", name: "거창군" }] },
  { slug: "gyeongnam-48890", metro: "gyeongnam", name: "합천군", fullName: "경상남도 합천군", lawdCodes: ["48890"], districts: [{ code: "48890", name: "합천군" }] },
  { slug: "jeju-50110", metro: "jeju", name: "제주시", fullName: "제주특별자치도 제주시", lawdCodes: ["50110"], districts: [{ code: "50110", name: "제주시" }] },
  { slug: "jeju-50130", metro: "jeju", name: "서귀포시", fullName: "제주특별자치도 서귀포시", lawdCodes: ["50130"], districts: [{ code: "50130", name: "서귀포시" }] },
];
// count=182
